### ISSUE TITLE
Would Send you info about ISE (IllegalStateException) with AXE

### ISSUE THREAD

**Issue by suerion** [SrRapero720/WATERFrAMES#123]
### What the loader are you seeing the problem on?

Fabric 1.21.1 on 0.16.5

### Describe the bug

I use your mod, but it log some issues with AXE what i would inform you

Could you look on this error?
```
[14:17:48] [Worker-Main-6/ERROR]: Couldn't read tag list minecraft:mineable/axe from minecraft:tags/block/mineable/axe.json in data pack waterframes
java.lang.IllegalStateException: Not a JSON object: null
	at com.mojang.serialization.DataResult$Error.md0d6e54$owo$lambda$addStackTraceToException$0$0(DataResult.java:565) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.class_3503.method_33174(class_3503.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_3503.method_33176(class_3503.java:128) ~[server-intermediary.jar:?]
	at net.minecraft.class_3505.method_33181(class_3505.java:46) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

### Steps to reproduce

Start Server
Server Log ( Line 2244)
https://mclo.gs/sTBJhnd

### What version of the Waterframes are you using?

waterframes 2.1.6

**Comment by SrRapero720** [comment]
Fixed in 8dd71e7ec67484ac918b6134941701ab7d231aa8
