### ISSUE TITLE
NoSuchMethod blockEntityChangedWithoutNeighborUpdates Crash

### ISSUE THREAD

**Issue by HydraSquid** [SrRapero720/WATERFrAMES#27]
**Version:** 1.18.2/2.0.0-beta3
**CreativeCore:** v2.6.17
Replication steps:
- Place down a frame
- Input any URL and apply
- Game crashes

**Suggested fix:**
Use a different method or raise the minimum Forge version requirement to 40.2.9. The helper method was only added as of this PR:
https://github.com/MinecraftForge/MinecraftForge/pull/9235
 **40.2.9  [1.18.2] Add new helper without duplicate neighbor update call (#9235)**
 
<details>
<summary> latest.log Snippet </summary>

```log
[14:54:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.world.level.Level.blockEntityChangedWithoutNeighborUpdates(net.minecraft.core.BlockPos)'
	at me.srrapero720.waterframes.common.block.entity.DisplayTile.setDirty(DisplayTile.java:134) ~[waterframes-1.18.2-2.0.0-beta3.jar%23118!/:2.0.0-beta3]
	at me.srrapero720.waterframes.common.data.DisplayData.sync(DisplayData.java:250) ~[waterframes-1.18.2-2.0.0-beta3.jar%23118!/:2.0.0-beta3]
	at me.srrapero720.waterframes.common.data.FrameData.sync(FrameData.java:41) ~[waterframes-1.18.2-2.0.0-beta3.jar%23118!/:2.0.0-beta3]
	at me.srrapero720.waterframes.common.screen.FrameScreen.syncData(FrameScreen.java:152) ~[waterframes-1.18.2-2.0.0-beta3.jar%23118!/:2.0.0-beta3]
	at me.srrapero720.waterframes.common.screen.FrameScreen.syncData(FrameScreen.java:19) ~[waterframes-1.18.2-2.0.0-beta3.jar%23118!/:2.0.0-beta3]
	at me.srrapero720.waterframes.common.screen.DisplayScreen.lambda$new$5(DisplayScreen.java:38) ~[waterframes-1.18.2-2.0.0-beta3.jar%23118!/:2.0.0-beta3]
	at team.creative.creativecore.common.gui.sync.GuiSyncLocal.receive(GuiSyncLocal.java:24) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at team.creative.creativecore.common.gui.sync.GuiSyncLocal.receive(GuiSyncLocal.java:13) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at team.creative.creativecore.common.gui.packet.ControlSyncPacket.execute(ControlSyncPacket.java:30) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at team.creative.creativecore.common.gui.packet.LayerPacket.executeServer(LayerPacket.java:24) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at team.creative.creativecore.common.network.CreativePacket.execute(CreativePacket.java:16) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$4(CreativeNetwork.java:52) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at team.creative.creativecore.common.network.CreativeNetwork.lambda$registerType$5(CreativeNetwork.java:52) ~[CreativeCore_FORGE_v2.6.17_mc1.18.2.jar%2377!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:72) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[forge-1.18.2-40.2.4-universal.jar%23128!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:1439) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
</details>

**Comment by SrRapero720** [comment]
i has NO plans to keep compatibility with minimal Forge versions, specially with my recent contributions. New waterframes versión now uses a Forge versión range to restrict mod to the latest versión of Forge 1.18.2

Edit: Same with WATERMeDIA 2.1.x

**Comment by SrRapero720** [comment]
Was fixed in commit: https://github.com/SrRapero720/waterframes/commit/c43bfca4230b6e6b92926b234c7ad52b84a06dfe
