### ISSUE TITLE
Game crashes when right clicking on picture frame.  Exception in server tick loop.

### ISSUE THREAD

**Issue by IPissMapleSyrup** [SrRapero720/WATERFrAMES#44]
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-04-16 19:10:01
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: team/creative/creativecore/common/gui/controls/simple/GuiIconButton
	at me.srrapero720.waterframes.common.block.FrameBlock.create(FrameBlock.java:86) ~[waterframes-1.20.1-2.0.0-beta5.1.jar%23283!/:2.0.0-beta5.1] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.lambda$new$0(GuiCreator.java:107) ~[CreativeCore_FORGE_v2.11.26_mc1.20.1.jar%23247!/:2.11.26] {re:classloading}
	at team.creative.creativecore.common.gui.packet.OpenGuiPacket.openGuiOnServer(OpenGuiPacket.java:38) ~[CreativeCore_FORGE_v2.11.26_mc1.20.1.jar%23247!/:2.11.26] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator.openGui(GuiCreator.java:52) ~[CreativeCore_FORGE_v2.11.26_mc1.20.1.jar%23247!/:2.11.26] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.open(GuiCreator.java:120) ~[CreativeCore_FORGE_v2.11.26_mc1.20.1.jar%23247!/:2.11.26] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.open(GuiCreator.java:113) ~[CreativeCore_FORGE_v2.11.26_mc1.20.1.jar%23247!/:2.11.26] {re:classloading}
	at me.srrapero720.waterframes.common.block.DisplayBlock.m_6227_(DisplayBlock.java:73) ~[waterframes-1.20.1-2.0.0-beta5.1.jar%23283!/:2.0.0-beta5.1] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:backpacked.forge.mixins.json:common.ServerPlayerGameModeMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinServerPlayerGameMode,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin,pl:mixin:APP:bettercombat.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:backpacked.common.mixins.json:common.ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23296!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.lang.ClassNotFoundException: team.creative.creativecore.common.gui.controls.simple.GuiIconButton
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 373268008 bytes (355 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=30.0.101.2079
	Graphics card #1 name: NVIDIA GeForce MX130
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x174d
	Graphics card #1 versionInfo: DriverVersion=31.0.15.4626
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 16677.80
	Virtual memory used (MB): 12593.70
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 1037.00
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Syrup_Man'/78, l='ServerLevel[Hard Forge]', x=571.45, y=76.00, z=-122.96]]
	Data Packs: vanilla, mod:farmersdelight, mod:betterdungeons, mod:terrablender, mod:moonlight (incompatible), mod:endersdelight, mod:biomesoplenty (incompatible), mod:geckolib, mod:creativecore, mod:aether, mod:jei, mod:nethersdelight, mod:vegandelight, mod:aquaculturedelight, mod:rubidium, mod:flywheel, mod:curios (incompatible), mod:majruszsaccessories (incompatible), mod:create, mod:camera, mod:sit, mod:artifacts, mod:smarterfarmers (incompatible), mod:yungsapi, mod:mixinextras (incompatible), mod:betterstrongholds, mod:cumulus_menus, mod:twilightdelight (incompatible), mod:architectury (incompatible), mod:nitrogen_internals, mod:majruszsenchantments (incompatible), mod:aetherdelight, mod:l2library (incompatible), mod:cloth_config (incompatible), mod:forge, mod:aquaculture, mod:crabbersdelight, mod:expandability (incompatible), mod:bettermineshafts, mod:twilightforest, mod:delightful (incompatible), mod:majruszlibrary (incompatible), builtin/aether_accessories, builtin/aether_ruined_portal, mod:betterwitchhuts, mod:playeranimator (incompatible), mod:realmrpg_demons, mod:betteroceanmonuments, mod:goblintraders (incompatible), mod:realmrpg_creep, mod:realmrpg_skeletons, mod:citadel (incompatible), mod:alexsmobs (incompatible), mod:betterdeserttemples, mod:catalogue (incompatible), mod:jeresources, mod:betterfortresses, mod:useless_sword, mod:bettercombat (incompatible), mod:dogslie (incompatible), mod:born_in_chaos_v1, mod:seadwellers, mod:yungsextras, mod:backpacked (incompatible), mod:deeperdarker, mod:alexsdelight, mod:betterendisland, mod:framework, mod:realmrpg_wyrms, mod:pots_and_mimics, mod:betterjungletemples, mod:unusual_delight, mod:amendments (incompatible), mod:carryon (incompatible), mod:supplementaries, mod:mixinsquared (incompatible), Supplementaries Generated Pack, mod:spawnbalanceutility, mod:watermedia (incompatible), mod:aeroblender (incompatible), mod:deep_aether, mod:waterframes (incompatible), builtin/aether_lost_content_not_compat (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1-forge-47.2.0
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		YungsBetterDungeons-1.20-Forge-4.0.3.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.20-Forge-3.0.3.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		Unusual_Delight_2.2.jar                           |Unusual Delight               |unusual_delight               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		amendments-1.20-1.1.14.jar                        |Amendments                    |amendments                    |1.20-1.1.14         |DONE      |Manifest: NOSIGNATURE
		watermedia-2.0.31.jar                             |WaterMedia                    |watermedia                    |2.0.31              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.4.jar                   |GeckoLib 4                    |geckolib                      |4.4.4               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		aether-1.20.1-1.3.1-neoforge.jar                  |The Aether                    |aether                        |1.20.1-1.3.1-neoforg|DONE      |Manifest: NOSIGNATURE
		realmrpg_imps_and_demons_0.9.0_forge_1.20.1.jar   |Realm RPG: Imps & Demons      |realmrpg_demons               |0.9.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.4    |DONE      |Manifest: NOSIGNATURE
		vegandelight-1.1.jar                              |Vegan Delight                 |vegandelight                  |1.1                 |DONE      |Manifest: NOSIGNATURE
		goblintraders-forge-1.20.1-1.9.3.jar              |Goblin Traders                |goblintraders                 |1.9.3               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		realmrpg_creep_and_crop_1.0.2_forge_1.20.1.jar    |Realm RPG: Creep & Crop       |realmrpg_creep                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		aquaculture_delight_1.0.0_forge_1.20.1.jar        |Aquaculture Delight           |aquaculturedelight            |1.0.0               |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.20.1-0.7.1a.jar                      |Rubidium                      |rubidium                      |0.7.1a              |DONE      |Manifest: NOSIGNATURE
		realmrpg_fallen_adventurers_1.0.3_forge_1.20.1.jar|Realm RPG: Fallen Adventurers |realmrpg_skeletons            |1.0.3               |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.4-1.20.1.jar                          |Citadel                       |citadel                       |2.5.4               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.7.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.7              |DONE      |Manifest: NOSIGNATURE
		artifacts-forge-9.3.0.jar                         |Artifacts                     |artifacts                     |9.3.0               |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.20-1.8.3.jar                     |Smarter Farmers               |smarterfarmers                |1.20-1.8.3          |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.4.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.2.jar                       |MixinExtras                   |mixinextras                   |0.3.2               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		catalogue-forge-1.20.1-1.8.0.jar                  |Catalogue                     |catalogue                     |1.8.0               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.247.jar          |Just Enough Resources         |jeresources                   |1.4.0.247           |DONE      |Manifest: NOSIGNATURE
		aether_delight_1.0.0_forge_1.20.1.jar             |Aether Delight                |aetherdelight                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.6    |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.20.1-4.3.2145-universal.jar      |The Twilight Forest           |twilightforest                |4.3.2145            |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.8.10.jar                   |Supplementaries               |supplementaries               |1.20-2.8.10         |DONE      |Manifest: NOSIGNATURE
		spawnbalanceutility-1.20-46.13.3.jar              |SpawnBalanceUtility           |spawnbalanceutility           |46.13.3             |DONE      |Manifest: NOSIGNATURE
		useless-sword-1.20.1-V1.4.1.jar                   |Useless Sword                 |useless_sword                 |1.4.1               |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.4.jar             |TerraBlender                  |terrablender                  |3.0.1.4             |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.11.9-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.11.9         |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.8.4+1.20.1.jar               |Better Combat                 |bettercombat                  |1.8.4+1.20.1        |DONE      |Manifest: NOSIGNATURE
		endersdelight-1.20.1-1.0.3.jar                    |Ender's Delight               |endersdelight                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		LetSleepingDogsLie-1.20.1-Forge-1.2.0.jar         |Let Sleeping Dogs Lie         |dogslie                       |1.2.0               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.26_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.26             |DONE      |Manifest: NOSIGNATURE
		nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		born_in_chaos_[Forge]1.20.1_1.2.jar               |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		aeroblender-1.20.1-1.0.2-rc1-neoforge.jar         |AeroBlender                   |aeroblender                   |1.20.1-1.0.2-rc1-neo|DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.3.5+1.20.1.jar                     |Curios API                    |curios                        |5.3.5+1.20.1        |DONE      |Manifest: NOSIGNATURE
		majruszs-accessories-forge-1.20.1-1.5.2.jar       |Majrusz's Accessories         |majruszsaccessories           |1.5.2               |DONE      |Manifest: NOSIGNATURE
		camera-1.20.1-1.0.6.jar                           |Camera Mod                    |camera                        |1.20.1-1.0.6        |DONE      |Manifest: NOSIGNATURE
		realmrpg_seadwellers_2.9.9_forge_1.20.1.jar       |Realm RPG: Sea Dwellers       |seadwellers                   |2.9.9               |DONE      |Manifest: NOSIGNATURE
		sit-1.20.1-1.3.4.jar                              |Sit                           |sit                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.20-Forge-4.0.3.jar                  |YUNG's Extras                 |yungsextras                   |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		backpacked-forge-1.20.1-2.2.5.jar                 |Backpacked                    |backpacked                    |2.2.5               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		cumulus_menus-1.20.1-1.0.0-neoforge.jar           |Cumulus                       |cumulus_menus                 |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		twilightdelight-2.0.10.jar                        |Twilight's Flavor & Delight   |twilightdelight               |2.0.10              |DONE      |Manifest: NOSIGNATURE
		deeperdarker-forge-1.20.1-1.2.1.jar               |Deeper and Darker             |deeperdarker                  |1.2.1               |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.5.jar                              |Alex's Delight                |alexsdelight                  |1.5                 |DONE      |Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.20-Forge-2.0.6.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.6    |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.20.1-2.5.1.jar                      |Aquaculture 2                 |aquaculture                   |2.5.1               |DONE      |Manifest: NOSIGNATURE
		nitrogen_internals-1.20.1-1.0.7-neoforge.jar      |Nitrogen                      |nitrogen_internals            |1.20.1-1.0.7-neoforg|DONE      |Manifest: NOSIGNATURE
		majruszs-enchantments-forge-1.20.1-1.10.7.jar     |Majrusz's Enchantments        |majruszsenchantments          |1.10.7              |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.27.jar                 |Framework                     |framework                     |0.6.27              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		l2library-2.4.16-slim.jar                         |L2 Library                    |l2library                     |2.4.16              |DONE      |Manifest: NOSIGNATURE
		deep_aether-1.20.1-1.0.2.jar                      |Deep Aether                   |deep_aether                   |1.20.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		CrabbersDelight-1.20.1-1.1.4.jar                  |Crabber's Delight             |crabbersdelight               |1.1.4               |DONE      |Manifest: NOSIGNATURE
		realmrpg_dragon_wyrms_1.0.1_forge_1.20.1.jar      |Realm RPG: Dragon Wyrms       |realmrpg_wyrms                |1.0.1               |DONE      |Manifest: NOSIGNATURE
		Delightful-1.20.1-3.5.2.jar                       |Delightful                    |delightful                    |3.5.2               |DONE      |Manifest: NOSIGNATURE
		expandability-forge-9.0.0.jar                     |ExpandAbility                 |expandability                 |9.0.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
		waterframes-1.20.1-2.0.0-beta5.1.jar              |WaterFrames                   |waterframes                   |2.0.0-beta5.1       |DONE      |Manifest: NOSIGNATURE
		majrusz-library-forge-1.20.1-7.0.5.jar            |Majrusz Library               |majruszlibrary                |7.0.5               |DONE      |Manifest: NOSIGNATURE
		realmrpg_pots_and_mimics_1.0.2_forge_1.20.1.jar   |Realm RPG: Pots & Mimics      |pots_and_mimics               |1.0.2               |DONE      |Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.20-Forge-2.0.4.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.4    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 76b6d092-9b3f-486b-99ed-749d42365a01
	FML: 47.2
	Forge: net.minecraftforge:47.2.0
	Flywheel Backend: GL33 Instanced Arrays
```

**Comment by SrRapero720** [comment]
downgrade creativecore to 1 version earlier, i am still waiting for another important CC update to use latets version

**Comment by IPissMapleSyrup** [comment]
Okay, thank you. I was thinking that might be the problem, but I wasn't sure.

**Comment by SrRapero720** [comment]
## ISSUE ADDRESSED, DOWNLOAD FIXED VERSION
- **CurseForge:** [1.18.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305775) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305778) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5305784)
