### ISSUE TITLE
Clientside crash after updating and loading specific chunk with WaterFrame

### ISSUE THREAD

**Issue by xhatz** [SrRapero720/WATERFrAMES#46]
Just as the title said, I updated the mod on my server and client to the latest pre-release version, but each time I load a chunk containing an old frame, the client crashes (server is fine).

Full latest.log: https://mclo.gs/14LbfIG.

```Thread: Render thread
Suspected Mod: 
	WaterFrames (waterframes), Version: 2.0.0-pre.4
		Issue tracker URL: https://github.com/SrRapero720/waterframes/issues
		at TRANSFORMER/waterframes@2.0.0-pre.4/me.srrapero720.waterframes.client.display.TextureDisplay.tick(TextureDisplay.java:149)
Stacktrace:
	at me.srrapero720.waterframes.client.display.TextureDisplay.tick(TextureDisplay.java:149) ~[waterframes-1.20.1-2.0.0-pre.4.jar%23374!/:2.0.0-pre.4] {re:classloading}
	at me.srrapero720.waterframes.common.block.entity.DisplayTile.tick(DisplayTile.java:179) ~[waterframes-1.20.1-2.0.0-pre.4.jar%23374!/:2.0.0-pre.4] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:waterframes.mixin.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:260) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.ClientLevelMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:waterdripsound.mixins.json:client.MixinClientWorld,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}```

**Comment by SrRapero720** [comment]
# 🗃️ I NEED YOUR LOGS TO DIAGNOSE
Your latest.log file is placed in your ``.minecraft/logs`` folder (instance folder), pickup the file and upload it into any website below. 
If your game crashes please also append the crash report in the ``.minecraft/crash-report`` folder.
Paste it here so i can help you more easier

# 🖥️ PASTE PAGES
- **Github (100MB)**: https://gist.github.com/
- **MCLogs (10MB)**: https://mclo.gs/
- **PasteGG (15MB)**: https://paste.gg/
- **PasteEE (1MB)**: https://paste.ee/
- **HasteBin (400kB)**: https://hastebin.com/
- **CentOS (1MB)**: https://paste.centos.org/

**Comment by xhatz** [comment]
Updated, sorry 😁

**Comment by SrRapero720** [comment]
aaja i need to release another watermedia update :/

**Comment by xhatz** [comment]
(WaterMedia 2.0.40 works, no crashes, by the way, if it's of any help to you :p)

**Comment by SrRapero720** [comment]
Issue addtressed by WATERMeDIA
