### ISSUE TITLE
Crash when opening the GUI on dedicated server

### ISSUE THREAD

**Issue by zFERDQFREZrzfq** [SrRapero720/WATERFrAMES#67]
Hello!

The latest version of waterframes introduced a new crash on dedicated server (only on dedicated, no issue on singleplayer).
It looks likes the mod tries to use a Blaze3D-related class, which does not exists on dedicated side.
```
`Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.mojang.blaze3d.vertex.PoseStack`

It looks like the cause is the GuiSliderMixin beeing applied on dedicated :
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [waterframes.mixin.json:creativecore.GuiSliderMixin from mod waterframes]`

Minecraft 1.20.1
Waterframes 2.0.6
CreativeCore 2.11.28
Forge 47.2.32

Here is the crash log :

Time: 2024-05-18 13:50:26
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar%2355!/:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at me.srrapero720.waterframes.common.block.FrameBlock.create(FrameBlock.java:77) ~[waterframes-1.20.1-2.0.6.jar%23573!/:2.0.6] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.lambda$new$0(GuiCreator.java:107) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28] {re:classloading}
	at team.creative.creativecore.common.gui.packet.OpenGuiPacket.openGuiOnServer(OpenGuiPacket.java:38) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator.openGui(GuiCreator.java:52) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28] {re:classloading,pl:runtimedistcleaner:A}
	at team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.open(GuiCreator.java:120) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28] {re:classloading}
	at team.creative.creativecore.common.gui.creator.GuiCreator$GuiCreatorBlock.open(GuiCreator.java:113) ~[CreativeCore_FORGE_v2.11.28_mc1.20.1.jar%23401!/:2.11.28] {re:classloading}
	at me.srrapero720.waterframes.common.block.DisplayBlock.m_6227_(DisplayBlock.java:68) ~[waterframes-1.20.1-2.0.6.jar%23573!/:2.0.6] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin from mod modernfix,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase from mod framedblocks,pl:mixin:APP:lithium.mixins.json:ai.pathing.AbstractBlockStateMixin from mod radium,pl:mixin:APP:lithium.mixins.json:util.block_tracking.AbstractBlockStateMixin from mod radium,pl:mixin:APP:pehkui.mixins.json:compat116plus.AbstractBlockStateMixin from mod pehkui,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin from mod starlight,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase from mod crafttweaker,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin from mod twigs,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin from mod ferritecore,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.BlockStateBaseMixin from mod expandability,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:antixray.mixins.json:ServerPlayerGameModeMixin from mod antixray,pl:mixin:APP:pehkui.mixins.json:reach.compat119plus.ServerPlayerInteractionManagerMixin from mod pehkui,pl:mixin:APP:fabric-events-interaction-v0.mixins.json:ServerPlayerInteractionManagerMixin from mod fabric_events_interaction_v0,pl:mixin:APP:item_obliterator.mixins.json:InteractionManagerMixin from mod item_obliterator,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-networking-api-v1.mixins.json:ServerPlayNetworkHandlerMixin from mod fabric_networking_api_v1,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin from mod modernfix,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin from mod supplementaries,pl:mixin:APP:krypton.mixins.json:shared.network.util.ServerPlayNetworkHandlerAccessor from mod krypton,pl:mixin:APP:pehkui.mixins.json:ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:pehkui.mixins.json:reach.compat119plus.ServerPlayNetworkHandlerMixin from mod pehkui,pl:mixin:APP:emotecraft.mixins.json:ServerPlayNetworkInstance from mod emotecraft,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinServerGamePacketListenerImpl from mod nochatreports,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin from mod railways,pl:mixin:APP:fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric_networking_api_v1,pl:mixin:APP:mixins.artifacts.common.json:item.umbrella.server.ServerGamePacketListenerImplMixin from mod artifacts,pl:mixin:APP:cpm.mixins.json:ServerGamePacketListenerImplMixin from mod cpm,pl:mixin:APP:expandability-common.mixins.json:swimming.server.ServerGamePacketListenerImplMixin from mod expandability,pl:mixin:APP:littletiles.mixins.json:server.network.ServerGamePacketListenerImplAccessor from mod littletiles,pl:mixin:APP:littletiles.mixins.json:server.network.ServerGamePacketListenerImplMixin from mod littletiles,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin from mod connectivity,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:computing_frames,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin from mod modernfix,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23587!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin from mod saturn,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin from mod balm,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin from mod fastload,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer from mod crafttweaker,pl:mixin:APP:fabric-message-api-v1.mixins.json:MinecraftServerMixin from mod fabric_message_api_v1,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin from mod citadel,pl:mixin:APP:serverpause.mixins.json:MinecraftServerAccessorMixin from mod serverpause,pl:mixin:APP:serverpause.mixins.json:MinecraftServerMixin from mod serverpause,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftServerMixin from mod connectormod,pl:mixin:APP:fabric-lifecycle-events-v1.mixins.json:MinecraftServerMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:MinecraftServerMixin from mod fabric_resource_loader_v0,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor from mod littletiles,pl:mixin:A,pl:connector_pre_launch:A}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin}
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [waterframes.mixin.json:creativecore.GuiSliderMixin from mod waterframes] from phase [DEFAULT] in config [waterframes.mixin.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	... 39 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> waterframes.mixin.json:creativecore.GuiSliderMixin from mod waterframes -> Apply Methods -> (Lcom/mojang/blaze3d/vertex/PoseStack;Ljava/lang/String;FFIZ)V:redirect$dkg000$waterframes$redirect$render -> Transform LVT -> var=pose -> desc=Lcom/mojang/blaze3d/vertex/PoseStack;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:510) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	... 39 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.mojang.blaze3d.vertex.PoseStack
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:1001) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:961) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:563) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:469) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:535) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:521) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[Connector-1.0.0-beta.43+1.20.1.jar%23342%23345!/:0.12.11+mixin.0.8.5] {}
	... 39 more

```

**Comment by SrRapero720** [comment]
DAMMIT
I forgot to properly rebase
Downgrade to 2.0.5

**Comment by zFERDQFREZrzfq** [comment]
I tried to fix it by just tagging the `redirect$render` method as client only, it seems to do the job XD
