### ISSUE TITLE
[CRASH] Cannot read accesswidener file [Fabric 0.16.0/1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [SrRapero720/WATERFrAMES#85]
Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod waterframes
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:529)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:527)
	... 3 more

[latest.log](https://github.com/user-attachments/files/16202754/latest.log)

**Comment by SrRapero720** [comment]
dude... FL 16 get released 2 days ago...

**Comment by pokesmells** [comment]
> dude... FL 16 get released 2 days ago...

Regardless of that, it still doesn't work on 0.15.11???

Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod waterframes
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:512)
	... 3 more
[latest.log](https://github.com/user-attachments/files/16215443/latest.log)

**Comment by pokesmells** [comment]
I don't understand what the issue would be even if that fabric loader version released an hour ago, A **bug** is a bug?

It doesn't matter if I reported it, or rather even when you fixed it, what matters is that as a user I reported to you so you knew LMAO do not understand what the "Bro..." was for, as a dev myself I would appreciate it if a user actually reported a bug

**Comment by SrRapero720** [comment]
my concern is more on fabric... i mean, why release a new update right now and specifically to break the most annoying feature as is AW. Port to fabric is not a happy experience
thanks for the report. i have to release a new waterframes update for fabric (Damn again)

**Comment by SrRapero720** [comment]
> Regardless of that, it still doesn't work on 0.15.11???

That information just make it worse because that was the version i was using to run my dev env and works... Something really cursed is happening behind fabric or i am not seeing something

**Comment by SrRapero720** [comment]
not just that, people has that version and loads, have other bugs but loads #84

**Comment by SrRapero720** [comment]
ok i spotted the culprit (wrong upload artifact was referenced), curseforge has the wrong version of the mod 😓 
for now, download it from modrinth

**Comment by SrRapero720** [comment]
CF download fixed
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5530573

**Comment by pokesmells** [comment]
> CF download fixed https://www.curseforge.com/minecraft/mc-mods/waterframes/files/5530573

Thank you for the reupload and I greatly appreciate your effort, have an amazing day
